version: "3"
services:
  fs_server:
    build: .
    container_name: fs_server
    ports:
     - "80:5000"
    volumes:
     - /home/ubuntu/getter-pusher/output/:/app/output
     - /home/ubuntu/getter-pusher/input/:/app/input